# -*- coding: utf-8 -*-

def generate_legend(fname):
    f = open(fname, "w+")
    f.write('digraph test {\n')
    f.write('graph [ratio=fill];\n')
    f.write('node [label=\"\\N\", fontsize=15, shape=plaintext];\n')
    f.write('graph [bb="0,0,352,154"];\n')
    f.write('legend [width=2,label=<\n')
    f.write('    <TABLE ALIGN="LEFT">\n')
    f.write('<TR>\n')
    f.write('      <TD COLSPAN="2"><B>Legend</B></TD>\n')
    f.write('     </TR>\n')
    f.write('        <TR>\n')
    f.write('            <TD bgcolor="coral">             </TD>\n')
    f.write('            <TD >0.85+</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="orangered"></TD>\n')
    f.write('            <TD >0.7-0.85</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="red"></TD>\n')
    f.write('            <TD >0.55-0.7</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="darkorange"></TD>\n')
    f.write('            <TD >0.4-0.55</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="orange"></TD>\n')
    f.write('            <TD >0.2-0.4</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="gold"></TD>\n')
    f.write('            <TD >0.1-0.2</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="lawngreen"></TD>\n')
    f.write('            <TD >0.05-0.1</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="green"></TD>\n')
    f.write('            <TD >1E-5-0.05</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="dodgerblue"></TD>\n')
    f.write('            <TD >1E-10-1E-5</TD>\n')
    f.write('</TR>\n')
    f.write('<TR>\n')
    f.write('            <TD bgcolor="purple"></TD>\n')
    f.write('            <TD >0.0-1E-10</TD>\n')
    f.write('</TR>\n')
    f.write('        \n')
    f.write('    </TABLE>\n')
    f.write('> ];\n')
    f.write('}\n')
    f.close()